**Perturbation Theory for Confined System**

Effect of confinement on the orbital energies of closed shell atom will be demonstrated using first order perturbation theory, where, the confinement potential can be taken as a pertubation onto unpertubed fock operator, to give us the perturbed confined hamiltonian as follows:

$\hat{H} = \hat{f} + \hat{H'}$

the eigenvalues and eigenvectors of this total hamiltonian of the confined sytem (perturbed system) can be related to the corrosponding eigenvalues and eigenvectors of the unpertubed system $\hat{f}$ via a perturbation parameter $\lambda$, so finally, the total hamiltonian can be written as, 

$\hat{H} = \hat{f} + \lambda \hat{H'}$

where, 

$\hat{H}$ : Perturbed Hamiltonian

$\hat{f}$ : Unpertubed Hamiltonian

$\lambda$ : Extent of perturbation

$\hat{H'}$ : Perturbation

using the derivations of perturbation theory, the first order correction in energy is given by, 

$E_{n}^{(1)}= \int_{-\infty}^{\infty} \phi_{n}^{(0)*} (r) \hat{H'}\phi_{n}^{(0)} (r) d\mathcal{T}$

where, R is the radius of confinement such that, 

$\phi_{n}^{0}(r) \rightarrow 0 , as  r \rightarrow R $

similarly, the first order correction in wavefucntion is given by, 

$\phi_{n}^{(1)} = \sum_{m \neq n}\frac{\int_{-\infty}^{\infty}\phi_{m}^{(0)*}\hat{H'}\phi_{n}^{(0)}d\mathcal{T}}{E_{n}^{(0)}-E_{m}^{(0)}}\phi_{m}^{(0)}$, 

and hence the total energy and resultant wavefucntion upto first order correction will be given by,

.........................................................................................

 $E_{n}=E_{n}^{(0)} + \int_{0}^{+oo} \phi_{n}^{(0)*}\hat{H'}\phi_{n}^{(0)} d\mathcal{T}$ 

.........................................................................................

and, 

.........................................................................................................................................................

$\phi_{n} = \phi_{n}^{(0)}  + \sum_{m \neq n}\frac{\int_{0}^{+oo}\phi_{m}^{(0)*}\hat{H'}\phi_{n}^{(0)}d\mathcal{T}}{E_{n}^{(0)}-E_{m}^{(0)}}\phi_{m}^{(0)}$

.........................................................................................................................................................

for ground state of the confined system, the above eqautions will be, 

$E_{0}=E_{0}^{(0)} + \int_{0}^{+oo} \phi_{0}^{(0)*}\hat{H'}\phi_{0}^{(0)} d\mathcal{T}$

and, 

$\phi_{0} = \phi_{0}^{(0)}  + \sum_{m \neq 0}\frac{\int_{0}^{+oo}\phi_{m}^{(0)*}\hat{H'}\phi_{0}^{(0)}d\mathcal{T}}{E_{0}^{(0)}-E_{m}^{(0)}}\phi_{m}^{(0)}$

In problem concerned, the perturbation $\hat{H'}$ is nothing but, the fullerene potential $\hat{V_{C_{60}}}(r)$


***Importing Libraries***

In [1]:
import comp
import scipy.linalg
import sympy as sp
import numpy as np
import matplotlib.pyplot as plt
from sympy import oo

***Defining Variables***

In [2]:
r,r1,r2,zeta=sp.symbols("r,r1,r2,zeta")
n=sp.symbols("n", integer=True)

***First Order Energy correction of orbital energies due to Speherical Square Well Potential***

Spherical square well potential is given by,

........................

for, $r\leq r_{1}$

........................

U(r)= 0

........................

for, $r_{1}< r <r_{2}$

........................

U(r)= 6eV = 0.22 au 

........................

and, $r\geq r_{2}$

........................

U(r) = 0

where, 

$r_{1} = 5.12$ au

$r_{2} = 8.12$ au

reference :-https://iopscience.iop.org/article/10.1088/0953-4075/43/11/115102 

In [41]:
def E_ssw(n, OrbE, Wavefucntions):
    
    r1=5.12
    r2=8.12
    
    e= OrbE[n] - sp.integrate( Wavefucntions[-1][n]*0.22*Wavefucntions[-1][n]*4*sp.pi*r*r, (r, r1, r2))
    
    info1=print('E_NC({})={:.7f}'.format(n,OrbE[n]))
    info2=print('E_C({})={:.7f}'.format(n, e))
    difference =print('\u0394 E= {:.7f}'.format(e-OrbE[n]))
    
    return info1, info2, difference

***First Order Energy correction of orbital energies due to approximated Fullerene Potential***

Approximated Fullerene Potential is, 

.......................................

for, $r_{c} \leq r \leq r_{c} + \delta$

.......................................

$\hat{V}_{C_{60}}(r) = -U_{0}   $
                       
..........

otherwise

..........

$-\frac{1}{r}    otherwise $

where, 

$r_{c}=5.75 $ au

$\delta = 1.89 $ au

$U_{0} = 8.22eV = 0.3021 $ au

In [42]:
def E_f1(n, OrbE, Wavefucntions, delta):
    r_c=5.75

    e1= - sp.integrate(Wavefucntions[-1][n]*Wavefucntions[-1][n]*4*sp.pi*r, (r, 0, r_c))
    e2= -sp.integrate(Wavefucntions[-1][n]*0.3021*Wavefucntions[-1][n]*4*sp.pi*r*r, (r, r_c, r_c + delta))
    e3= - sp.integrate(Wavefucntions[-1][n]*Wavefucntions[-1][n]*4*sp.pi*r, (r, r_c + delta, +oo))
    e = OrbE[n] + e1+ e2+ e3
    
    info1=print('E_NC({})={:.7f}'.format(n,OrbE[n]))
    info2=print('E_C({})={:.7f}'.format(n, e))
    difference =print('\u0394 E= {:.7f}'.format(e-OrbE[n]))
    
    return info1, info2, difference

***First Order Energy correction of orbital energies due to approximated Fullerene Potential***

for $0\leq r \leq r_{1}$

V(r) = 2.82

for $r_{1}\leq r \leq r_{2}$

V(r)= 0

for $r_{2}\leq r \leq R$

V(r) = 0.56

where, 

$r_{1}$ = 4.2

$r_{2}$ = 9.2

$R$ = 27.6

reference:- https://link.springer.com/article/10.1134/S0036023619010212

In [1]:
def E_f2(n, OrbE, Wavefucntions):

    e1=  sp.integrate(Wavefucntions[-1][n]*Wavefucntions[-1][n]*2.82*4*sp.pi*r**2, (r, 0, 4.2))
    e2= sp.integrate(Wavefucntions[-1][n]*0*Wavefucntions[-1][n]*4*sp.pi*r*r, (r, 4.2, 9.2))
    e3=  sp.integrate(Wavefucntions[-1][n]*0.56*Wavefucntions[-1][n]*4*sp.pi*r**2, (r, 9.2, 27.6))
    e = OrbE[n] + e1+ e2+ e3
    
    info1=print('E_NC({})={:.7f}'.format(n,OrbE[n]))
    info2=print('E_C({})={:.7f}'.format(n, e))
    difference =print('\u0394 E= {:.7f}'.format(e-OrbE[n]))
    
    return info1, info2, difference

***First Order Energy correction of orbital energies due to approximated Fullerene Potential***

for 5.75< r < 7.64

V(r) = -0.302

for  r < 5.75 or r > 7.64 

V(r)= 0

reference:- https://ui.adsabs.harvard.edu/abs/2005CaJPh..83..919P/abstract

In [44]:
def E_f3(n, OrbE, Wavefucntions):
    r_c=5.75

    e1= sp.integrate(Wavefucntions[-1][n]*0*Wavefucntions[-1][n]*4*sp.pi*r*r, (r, 0, 5.75))
    e2= -sp.integrate(Wavefucntions[-1][n]*0.302*Wavefucntions[-1][n]*4*sp.pi*r**2, (r, 5.75, 7.64))
    e3= sp.integrate(Wavefucntions[-1][n]*Wavefucntions[-1][n]*2.82*4*sp.pi*r**2, (r, 7.64, +oo))
    e = OrbE[n] + e1+ e2+ e3
    
    info1=print('E_NC({})={:.7f}'.format(n,OrbE[n]))
    info2=print('E_C({})={:.7f}'.format(n, e))
    difference =print('\u0394 E= {:.7f}'.format(e-OrbE[n]))
    
    return info1, info2, difference

***Calling Atomic Data***

In [6]:
calculated1, Coef1, OrbE1, Wavefunctions1, OrbitalEnergies1, Densities1 = comp.element1()


---------------------------------------------------------------Intialization of SCF Calculation-------------------------------------------------------------------
-----------------------------------------------------------------Caclulating the Base Matrices--------------------------------------------------------------------
Overlap Matrix S
[[1.         0.83752358]
 [0.83752358 1.        ]]
Core Hamiltonian Matrix H
[[-1.85073991 -1.88346692]
 [-1.88346692 -1.58510327]]
Orbital Coefficent Matrix Coef
[[-0.66167683  1.70635831]
 [-0.37818627 -1.79065632]]
Density Matrix
[[0.87563244 0.50047418]
 [0.50047418 0.28604971]]
Orbital Energies
E1=-1.9796197 Hartree
E2=1.0385938 Hartree
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
E_0= -3.9592393540595534
Delta E=1.0000000
time=0.26s
------------------------------------------------------------Evaluation of Two Electron Integr

In [7]:
calculated2, Coef2, OrbE2, Wavefunctions2,OrbitalEnergies2, Densities2 = comp.element2()


---------------------------------------------------------------Intialization of SCF Calculation-------------------------------------------------------------------
-----------------------------------------------------------------Caclulating the Base Matrices--------------------------------------------------------------------
Overlap Matrix S
[[1.         0.90780473 0.09913506 0.03600389]
 [0.90780473 1.         0.24088162 0.10010333]
 [0.09913506 0.24088162 1.         0.85384478]
 [0.03600389 0.10010333 0.85384478 1.        ]]
Core Hamiltonian Matrix H
[[-6.73423222 -7.72797915 -1.2023588  -0.44433419]
 [-7.72797915 -7.79223253 -1.58200291 -0.6488039 ]
 [-1.2023588  -1.58200291 -1.85201235 -1.30794285]
 [-0.44433419 -0.6488039  -1.30794285 -1.15798333]]
Orbital Coefficent Matrix Coef
[[-0.27496359  0.12692838  0.04836581 -2.55587145]
 [-0.75137793  0.11341183  0.04651207  2.57678463]
 [ 0.05166651 -1.54246714 -1.22132795 -0.87869877]
 [-0.03145212  0.68332305  1.81939035  0.57627982]]


In [8]:
calculated_i, Coef_i, OrbE_i, Wavefunctions_i,OrbitalEnergies_i, Densities_i= comp.ion1()


---------------------------------------------------------------Intialization of SCF Calculation-------------------------------------------------------------------
-----------------------------------------------------------------Caclulating the Base Matrices--------------------------------------------------------------------
Overlap Matrix S
[[1.         0.91285073 0.80836749]
 [0.91285073 1.         0.9737909 ]
 [0.80836749 0.9737909  1.        ]]
Core Hamiltonian Matrix H
[[-7.83795445 -7.72673217 -7.23809647]
 [-7.72673217 -6.66910387 -5.12805201]
 [-7.23809647 -5.12805201 -2.38395848]]
Orbital Coefficent Matrix Coef
[[  0.62854634  -3.64869682   3.24524536]
 [  0.55388456   6.49598562 -10.94870937]
 [ -0.17584556  -2.97528845   8.32038814]]
Density Matrix
[[ 0.79014101  0.69628423 -0.22105416]
 [ 0.69628423  0.61357622 -0.19479628]
 [-0.22105416 -0.19479628  0.06184332]]
Orbital Energies
E1=-7.9973273 Hartree
E2=0.4759422 Hartree
E3=45.4657987 Hartree
------------------------------

**Change in Orbital Energies of Helium Atom due to several approximated fullerene confinements**

***Potential 1***

In [45]:
print('He - 1s2')
print('***********')
print('***********')
for n in range(len(OrbE1)):   
    E_ssw(n, OrbE1, Wavefunctions1)
    print('**************************')

He - 1s2
***********
***********
E_NC(0)=-0.9179354
E_C(0)=-0.9179422
Δ E= -0.0000068
**************************
E_NC(1)=2.8209572
E_C(1)=2.8209320
Δ E= -0.0000252
**************************


***Potential 2***

In [46]:
print('He - 1s2')
print('***********')
print('***********')
for n in range(len(OrbE1)):   
    E_f1(n, OrbE1, Wavefunctions1, 1.89)
    print('**************************')

He - 1s2
***********
***********
E_NC(0)=-0.9179354
E_C(0)=-1.9528811
Δ E= -1.0349457
**************************
E_NC(1)=2.8209572
E_C(1)=-1.0129983
Δ E= -3.8339555
**************************


***Potential 3***

In [47]:
print('He - 1s2')
print('***********')
print('***********')
for n in range(len(OrbE1)):   
    E_f2(n, OrbE1, Wavefunctions1)
    print('**************************')

He - 1s2
***********
***********
E_NC(0)=-0.9179354
E_C(0)=1.0889504
Δ E= 2.0068858
**************************
E_NC(1)=2.8209572
E_C(1)=10.2554643
Δ E= 7.4345071
**************************


***Potential 4***

In [48]:
print('He - 1s2')
print('***********')
print('***********')
for n in range(len(OrbE1)):   
    E_f3(n, OrbE1, Wavefunctions1)
    print('**************************')

He - 1s2
***********
***********
E_NC(0)=-0.9179354
E_C(0)=-0.9179371
Δ E= -0.0000017
**************************
E_NC(1)=2.8209572
E_C(1)=2.8209508
Δ E= -0.0000064
**************************


**Change in Orbital Energies of Berrylium Atom due to several approximated fullerene confinements**

***Spherical Square Well***

In [49]:
print('Be - 1s2 2s2')
print('***********')
print('***********')
for n in range(len(OrbE2)):   
    E_ssw(n, OrbE2, Wavefunctions2)
    print('**************************')

Be - 1s2 2s2
***********
***********
E_NC(0)=-4.7328298
E_C(0)=-4.7328298
Δ E= 0.0000000
**************************
E_NC(1)=-0.3092326
E_C(1)=-0.3092326
Δ E= 0.0000000
**************************
E_NC(2)=0.1448125
E_C(2)=0.1448125
Δ E= 0.0000000
**************************
E_NC(3)=11.3778938
E_C(3)=11.3778938
Δ E= 0.0000000
**************************


***Potential 1***

In [50]:
print('Be - 1s2 2s2')
print('***********')
print('***********')
for n in range(len(OrbE2)):   
    E_f1(n, OrbE2, Wavefunctions2, 1.89)
    print('**************************')

Be - 1s2 2s2
***********
***********
E_NC(0)=-4.7328298
E_C(0)=-4.8671952
Δ E= -0.1343654
**************************
E_NC(1)=-0.3092326
E_C(1)=-0.3092840
Δ E= -0.0000513
**************************
E_NC(2)=0.1448125
E_C(2)=0.1355920
Δ E= -0.0092205
**************************
E_NC(3)=11.3778938
E_C(3)=-25.5279503
Δ E= -36.9058441
**************************


***Potential 2***

In [20]:
print('Be - 1s2 2s2')
print('***********')
print('***********')
for n in range(len(OrbE2)):   
    E_f2(n, OrbE2, Wavefunctions2)
    print('**************************')

Be - 1s2 2s2
***********
***********
E_NC(0)=-4.7328298
E_C(0)=0.0677705
Δ E= 4.8006003
**************************
E_NC(1)=-0.3092326
E_C(1)=0.0000259
Δ E= 0.3092585
**************************
E_NC(2)=0.1448125
E_C(2)=0.0046506
Δ E= 0.1401619
**************************
E_NC(3)=11.3778938
E_C(3)=18.6143787
Δ E= 7.2364848
**************************


***Potential 3***

In [26]:
print('Be - 1s2 2s2')
print('***********')
print('***********')
for n in range(len(OrbE2)):   
    E_f3(n, OrbE2, Wavefunctions2)
    print('**************************')

Be - 1s2 2s2
***********
***********
E_NC(0)=-4.7328298
E_C(0)=-0.0000000
Δ E= 4.7328298
**************************
E_NC(1)=-0.3092326
E_C(1)=-0.0000000
Δ E= 0.3092326
**************************
E_NC(2)=0.1448125
E_C(2)=-0.0000000
Δ E= 0.1448125
**************************
E_NC(3)=11.3778938
E_C(3)=-0.0000000
Δ E= 11.3778938
**************************


**Change in Orbital Energies of Berrylium Ion due to several approximated fullerene confinements**

***Spherical Square Well***

In [51]:
print('Be2+ - 1s2')
print('***********')
print('***********')
for n in range(len(OrbE_i)):   
    E_ssw(n, OrbE_i, Wavefunctions_i)
    print('**************************')

Be2+ - 1s2
***********
***********
E_NC(0)=-5.6671201
E_C(0)=-5.6671201
Δ E= -0.0000000
**************************
E_NC(1)=3.4762126
E_C(1)=3.4762126
Δ E= -0.0000000
**************************
E_NC(2)=50.5421735
E_C(2)=50.5421735
Δ E= -0.0000000
**************************


***Potential 1***

In [52]:
print('Be2+ - 1s2')
print('***********')
print('***********')
for n in range(len(OrbE_i)):   
    E_f1(n, OrbE_i, Wavefunctions_i, 1.89)
    print('**************************')

Be2+ - 1s2
***********
***********
E_NC(0)=-5.6671201
E_C(0)=-8.4370430
Δ E= -2.7699229
**************************
E_NC(1)=3.4762126
E_C(1)=-42.2328834
Δ E= -45.7090959
**************************
E_NC(2)=50.5421735
E_C(2)=15.8618921
Δ E= -34.6802814
**************************


***Potential 2***

In [53]:
print('Be2+ - 1s2')
print('***********')
print('***********')
for n in range(len(OrbE_i)):   
    E_f2(n, OrbE_i, Wavefunctions_i)
    print('**************************')

Be2+ - 1s2
***********
***********
E_NC(0)=-5.6671201
E_C(0)=-3.3902787
Δ E= 2.2768414
**************************
E_NC(1)=3.4762126
E_C(1)=41.0485082
Δ E= 37.5722957
**************************
E_NC(2)=50.5421735
E_C(2)=79.0489239
Δ E= 28.5067504
**************************


***Potential 3***

In [54]:
print('Be2+ - 1s2')
print('***********')
print('***********')
for n in range(len(OrbE_i)):   
    E_f3(n, OrbE_i, Wavefunctions_i)
    print('**************************')

Be2+ - 1s2
***********
***********
E_NC(0)=-5.6671201
E_C(0)=-5.6671201
Δ E= -0.0000000
**************************
E_NC(1)=3.4762126
E_C(1)=3.4762126
Δ E= -0.0000000
**************************
E_NC(2)=50.5421735
E_C(2)=50.5421735
Δ E= -0.0000000
**************************
